name: Website Monitoring Automation

on:
  schedule:
    - cron: '30 12 * * *'

  workflow_dispatch:

jobs:
  monitor:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull Latest Changes
        run: |
          git pull origin main

      - name: Run Monitoring Script
        env:
          TZ: Asia/Kolkata
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

        run: |
          python monitor.py

      - name: Commit and Push Logs and Screenshots
        run: |

          git config --global user.name "github-actions"

          git config --global user.email "github-actions@github.com"

          git pull origin main

          git add monitoring_log.csv screenshots/

          git commit -m "Updated monitoring logs and screenshots" || echo "No changes to commit"

          git push origin main

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: monitoring_log.csv